name             'consul-test-helpers'
maintainer       'Adam Krone'
maintainer_email 'krone.adam@gmail.com'
license          'Apache v2.0'
description      'Installs/Configures consul-test-helpers'
long_description 'Installs/Configures consul-test-helpers'
version          '0.1.0'

depends 'curl'
depends 'consul-template'
